# Don't erase the following import if you want to use the db object
from models.domain import Domain
from models.role import Role
from models.user import User
from models.speaker import Speaker
from models.composer import Composer
from models.metadata import Metadata
from models.meta_value import MetaValue
from models.meta_key import MetaKey
from models.language import Language
from models.asset import Asset
from models.status_by_domain import StatusByDomain
from models.step_lifecycle import StepLifecycle
from models.booking import Booking
from models.room import Room
from models.captation import Captation
from models.type import Type
from models.post_prod import PostProd
from models.transformation import Transformation
from models.asset_translated import AssetTranslated
from models.subtitle import Subtitle
