version: '3.1'

services:
    dam-backoffice-api:
        container_name: dam-backoffice-api
        build:
            context: .
            dockerfile: pythonDockerfile
        ports:
            - '8004:8000'
        volumes:
            - ./flask_app/:/code
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        depends_on:
            - db
        networks:
            - appNetwork
        restart: always

    db:
        container_name: postgresql
        image: postgres:14.8
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - '5432'
        volumes:
            - db:/var/lib/postgres
        networks:
            - appNetwork


volumes:
    db:

networks:
   appNetwork:
        driver: bridge