version: '3.1'

services:
    dam-backoffice-api:
        container_name: dam-backoffice-api
        build:
            context: .
            dockerfile: dockerfile/Dockerfile-api
        ports:
            - '8004:8000'
        volumes:
            - ./flask_app:/code
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        depends_on:
            - db
        restart: always

    db:
        container_name: dam-postgresql
        image: postgres:14.8
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - '5432'
        volumes:
            - db:/var/lib/postgres

    front:
        container_name: dam-front
        build:
            context: .
            dockerfile: dockerfile/Dockerfile-front
        volumes:
            - ./front/src:/app/src
        restart: always
        ports:
            - '80:5173'
        depends_on:
            - dam-backoffice-api

    
volumes:
    db: