version: '3.1'

services:
    dam-backoffice-api:
        container_name: dam-backoffice-api
        build:
            context: .
            dockerfile: pythonDockerfile
        ports:
            - '8004:8000'
        environment:
            - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/data
        depends_on:
            - db
        links:
            - db
        networks:
            - appNetwork

    db:
        container_name: postgresql
        image: postgres:14.8
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=data
        expose:
            - '5432'
        volumes:
            - db:/var/lib/postgres
        networks:
            - appNetwork


volumes:
    db:

networks:
   appNetwork:
        driver: bridge