version: '3.1'

services:
    db:
        container_name: dam-postgresql
        image: postgres:14.8
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - '5432'
        volumes:
            - db:/var/lib/postgres

    front:
        container_name: dam-front
        image: nginx:latest
        ports:
            - '80:80'

volumes:
    db: