import { error } from '@sveltejs/kit';
  
export function load() {
    return {
        metadata:{
            instruments: ["piano","violon","guitare","violoncelle","trombone","harpe","trompette","flute"],
            categorie: ["concert", "interview", "masterclass"],
            rating: [1,2,3,4],
            role: ["superadmin","admin","user"], 
            domain: ["post-prod","regisseur","traducteur","editeur"], 
            translations: ["Français","Anglais","Italien","Espagnol","Allemand","Japonais","Russe","Arabe","Chinois","Coréen","Portugais"],
            style: ["classical","jazz","medieval"],
            era: ["XII","XVI","XVIII","XIX","XX"]
        },
        asset: [
            {
                id: 1,
                title: "Interview 1",
                has_high_priority: 1,
                instruments: ["piano","violon","guitare"],
                categorie: "interview",
                rating: 3,
                language: "français",
                created_at: "2023-05-01",
                status_by_domain: "traduction",
                published_at: "2023-06-01",
                last_assignment_date: "2023-05-06",
                name_by_domain: "Jean-Charles",
                rush_received: 1,
                version: 1,
                captation_done: 1,
                translations: ["Français","Anglais"]
            },
            {
                id: 2,
                title: "Interview 2",
                has_high_priority: 1,
                instruments: ["piano","violon","guitare"],
                categorie: "interview",
                rating: 4,
                language: "anglais",
                created_at: "2023-04-05",
                status_by_domain: "post-ptoduction",
                published_at: "2023-05-05",
                last_assignment_date: "2023-04-08",
                name_by_domain: "Jean-Pierre",
                rush_received: 0,
                version: 4,
                captation_done: 0,
                translations: ["Français","Allemand"]
            },
            {
                id: 3,
                title: "Concert de Jean Mich",
                has_high_priority: 0,
                instruments: ["piano","violon","guitare"],
                categorie: "concert",
                rating: 1,
                language: "japonais",
                created_at: "2023-01-12",
                status_by_domain: "édition",
                published_at: "2023-02-12",
                last_assignment_date: "2023-01-14",
                name_by_domain: "",
                rush_received: 1,
                version: 3,
                captation_done: 1,
                translations: ["Russe","Espagnol","Chinois"]
            },
            {
                id: 4,
                title: "Concert de Sabine Wesh",
                has_high_priority: 0,
                instruments: ["piano","trombone"],
                categorie: "concert",
                rating: 1,
                language: "italien",
                created_at: "2022-09-22",
                status_by_domain: "captation",
                published_at: "2022-10-22",
                last_assignment_date: "2022-09-25",
                name_by_domain: "Jean-Charles",
                rush_received: 0,
                version: 1,
                captation_done: 0,
            },
            {
                id: 5,
                title: "Masterclass sur la mélodie romantique",
                has_high_priority: 1,
                instruments: ["piano","violon","guitare"],
                categorie: "masterclass",
                rating: 5,
                language: "anglais",
                created_at: "2023-03-28",
                status_by_domain: "traduction",
                published_at: "2023-04-28",
                last_assignment_date: "2023-03-30",
                name_by_domain: "",
                rush_received: 0,
                version: 6,
                captation_done: 0,
            },
            {
                id: 6,
                title: "Masterclass sur l'intensité de jeu",
                has_high_priority: 0,
                instruments: ["piano","violon","violoncelle"],
                categorie: "masterclass",
                rating: 3,
                language: "français",
                created_at: "2022-08-15",
                status_by_domain: "édition",
                published_at: "2022-09-15",
                last_assignment_date: "2022-08-20",
                name_by_domain: "Jean-Paul",
                rush_received: 1,
                version: 1,
                captation_done: 1,
            }
        ],
        users:[
            {
                id: 1,
                fullname: 'Chloé Doustalet',
                email: 'test@gmail.com',
                role: 'user',
                profile_pic: 'https://cdn.shopify.com/s/files/1/0442/6219/5368/files/3I3A1369-2.jpg?v=1685536090',
                count_assigning_asset: 3,
                domain: 'regisseur'
            },
            {
                id: 2,
                fullname: 'Nassim Yazi',
                email: 'nassim@gmail.com',
                role: 'admin',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'édition',
                count_assigning_asset: 1,
            },
            {
                id: 3,
                fullname: 'Julia Doustalet',
                email: 'julia@gmail.com',
                role: 'admin',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'traduction',
            },
            {
                id: 4,
                fullname: 'Doriane Farau',
                email: 'doriane@gmail.com',
                role: 'user',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'captation',
            },
            {
                id: 5,
                fullname: 'Zoé Logeais',
                email: 'zoe@gmail.com',
                role: 'superadmin',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'édition',
            }
        ],
        booking:{
            room: [ 'Salle 1', 'Salle 2', 'Salle 3' ],
            time_slot: ['8h - 10h', '10h - 12h', '12h - 14h', '14h - 16h', '16h - 18h', '18h - 20h']
        },
        composer:[ "Compositeur 1","Compositeur 2","Compositeur 3","Compositeur 4","Compositeur 5" ],
        intervenor:[ "Intervenant 1","Intervenant 2","Intervenant 3","Intervenant 4","Intervenant 5" ],
    };
}