export function load() {
    return {
        metadata:{
            instruments: ["piano","violon","guitare","violoncelle","trombone","harpe","trompette","flute"],
            categorie: ["masterclass", "concert", "interview"],
            rating: [1,2,3,4],
            role: ["superadmin","admin","user"]
        },
        asset: [
            {
                id: 1,
                title: "Interview 1",
                has_high_priority: 1,
                instruments: ["piano","violon","guitare"],
                categorie: "interview",
                rating: 3,
                language: "français",
                created_at: "2023-05-01",
                status_by_domain: "traduction",
                published_at: "2023-06-01",
                last_assignment_date: "2023-05-06",
                name_by_domain: "Jean-Charles",
                rush_received: 1,
                version: 1,
                captation_done: 1,
            },
            {
                id: 2,
                title: "Interview 2",
                has_high_priority: 1,
                instruments: ["piano","violon","guitare"],
                categorie: "interview",
                rating: 4,
                language: "anglais",
                created_at: "2023-04-05",
                status_by_domain: "post-ptoduction",
                published_at: "2023-05-05",
                last_assignment_date: "2023-04-08",
                name_by_domain: "Jean-Pierre",
                rush_received: 0,
                version: 4,
                captation_done: 0,
            },
            {
                id: 3,
                title: "Concert de Jean Mich",
                has_high_priority: 0,
                instruments: ["piano","violon","guitare"],
                categorie: "concert",
                rating: 1,
                language: "japonais",
                created_at: "2023-01-12",
                status_by_domain: "édition",
                published_at: "2023-02-12",
                last_assignment_date: "2023-01-14",
                name_by_domain: "",
                rush_received: 1,
                version: 3,
                captation_done: 1,
            },
            {
                id: 4,
                title: "Concert de Sabine Wesh",
                has_high_priority: 0,
                instruments: ["piano","trombone"],
                categorie: "concert",
                rating: 1,
                language: "italien",
                created_at: "2022-09-22",
                status_by_domain: "captation",
                published_at: "2022-10-22",
                last_assignment_date: "2022-09-25",
                name_by_domain: "Jean-Charles",
                rush_received: 0,
                version: 1,
                captation_done: 0,
            },
            {
                id: 5,
                title: "Masterclass sur la mélodie romantique",
                has_high_priority: 1,
                instruments: ["piano","violon","guitare"],
                categorie: "masterclass",
                rating: 5,
                language: "anglais",
                created_at: "2023-03-28",
                status_by_domain: "traduction",
                published_at: "2023-04-28",
                last_assignment_date: "2023-03-30",
                name_by_domain: "",
                rush_received: 0,
                version: 6,
                captation_done: 0,
            },
            {
                id: 6,
                title: "Masterclass sur l'intensité de jeu",
                has_high_priority: 0,
                instruments: ["piano","violon","violoncelle"],
                categorie: "masterclass",
                rating: 3,
                language: "français",
                created_at: "2022-08-15",
                status_by_domain: "édition",
                published_at: "2022-09-15",
                last_assignment_date: "2022-08-20",
                name_by_domain: "Jean-Paul",
                rush_received: 1,
                version: 1,
                captation_done: 1,
            }
        ],
        users:[
            {
                id: 1,
                fullname: 'Chloé Doustalet',
                email: 'test@gmail.com',
                role: 'user',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'traduction',
            },
            {
                id: 2,
                fullname: 'Nassim Yazi',
                email: 'nassim@gmail.com',
                role: 'admin',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'édition',
            },
            {
                id: 3,
                fullname: 'Julia Doustalet',
                email: 'julia@gmail.com',
                role: 'admin',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'traduction',
            },
            {
                id: 4,
                fullname: 'Doriane Farau',
                email: 'doriane@gmail.com',
                role: 'user',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'captation',
            },
            {
                id: 5,
                fullname: 'Zoé Logeais',
                email: 'zoe@gmail.com',
                role: 'superadmin',
                profile_pic: 'https://fakeimg.pl/40x40/',
                domain: 'édition',
            }
        ]
    };
}