FROM node:lts-slim as base
WORKDIR /app
COPY ./front/ .
RUN npm install

FROM base as dev
ENTRYPOINT [ "npm", "run", "dev", "--", "--host"]

FROM base as prod
RUN npm run build
ENTRYPOINT [ "npm", "run", "start" ]