FROM node:lts-slim as base
WORKDIR /app
COPY ./front/ .
RUN npm ci

FROM base as DEV
ENTRYPOINT [ "npm", "run", "dev", "--", "--host"]

FROM base as PROD
RUN npm run build
ENTRYPOINT [ "npm", "run", "start" ]