name: Deploy

# TO UPDATE
on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ "main", "develop" ]
    types:
      - completed
  workflow_dispatch:


jobs:

  deploy:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.PROD_REGISTRY_TOKEN || secrets.PREPROD_REGISTRY_TOKEN }}
      REGISTRY_URL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_REGISTRY_URL || secrets.PREPROD_REGISTRY_URL }}
      REGISTRY_USER: ${{ github.ref == 'refs/heads/main' && secrets.PROD_REGISTRY_USER || secrets.PREPROD_REGISTRY_USER }}
      USERNAME: ${{ github.ref == 'refs/heads/main' && secrets.PROD_CD_USERNAME || secrets.PREPROD_CD_USERNAME }}
      HOST: ${{ github.ref == 'refs/heads/main' && secrets.PROD_CD_HOST || secrets.PREPROD_CD_HOST }}


    steps:
      - name: SSH
        uses: webfactory/ssh-agent@v0.5.2
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

      - name: Deploy
        run: ssh "${{ env.USERNAME }}"@"${{ env.HOST }}" \
          'docker compose pull && docker compose up -d'

      - name: Login to Registery
        run: ssh "${{ env.USERNAME }}"@"${{ env.HOST }}" 'echo "${{ env.TOKEN }}" | docker login "${{ env.REGISTRY_URL }}" -u "${{ env.REGISTRY_USER }}" --password-stdin'

