name: Deploy

# TO UPDATE
on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed
  workflow_dispatch:


jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: echo 'Todo Deployment'
