name: Deploy

# TO UPDATE
on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ "main", "develop" ]
    types:
      - completed
  workflow_dispatch:


jobs:

  deploy:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ github.event.pull_request.base.ref == 'main' && secrets.PROD_REGISTRY_TOKEN || secrets.PREPROD_REGISTRY_TOKEN }}
      REGISTRY_URL: ${{ github.event.pull_request.base.ref == 'main' && secrets.PROD_REGISTRY_URL || secrets.PREPROD_REGISTRY_URL }}
      REGISTRY_USER: ${{ github.event.pull_request.base.ref == 'main' && secrets.PROD_REGISTRY_USER || secrets.PREPROD_REGISTRY_USER }}
      USERNAME: ${{ github.event.pull_request.base.ref == 'main' && secrets.PROD_CD_USERNAME || secrets.PREPROD_CD_USERNAME }}
      HOST: ${{ github.event.pull_request.base.ref == 'main' && secrets.PROD_CD_HOST || secrets.PREPROD_CD_HOST }}


    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.2

      - name: SSH init
        run: |
          mkdir -p ~/.ssh
          cd ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      # Perform your desired actions that require SSH access here
      - name: Run SSH command
        run: ssh "${{ env.USERNAME }}"@"${{ env.HOST }}" "echo Hello, SSH!"

      - name: Deploy
        run: echo ${{ secrets.SSH_PRIVATE_KEY }} | ssh -i /dev/stdin cd_deploy@"${{ secrets.PROD_CD_HOST }}" \ 
          'docker compose pull && docker compose up -d'

      - name: Login to Registery
        run: ssh "${{ env.USERNAME }}"@"${{ env.HOST }}" 'echo "${{ env.TOKEN }}" | docker login "${{ env.REGISTRY_URL }}" -u "${{ env.REGISTRY_USER }}" --password-stdin'

