name: CI

# TO UPDATE
on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:

  build-test-push:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ github.event.pull_request.base.ref == 'main' && secrets.PROD_REGISTRY_TOKEN || secrets.PREPROD_REGISTRY_TOKEN }}
      REGISTRY_URL: ${{ github.event.pull_request.base.ref  == 'main' && secrets.PROD_REGISTRY_URL || secrets.PREPROD_REGISTRY_URL }}
      REGISTRY_USER: ${{ github.event.pull_request.base.ref  == 'main' && secrets.PROD_REGISTRY_USER || secrets.PREPROD_REGISTRY_USER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Test Echo
        run: echo ${{github.event.pull_request.base.ref}}

      - name: Build Docker Images
        run: docker buildx build . --file ./dockerfile/Dockerfile-api --tag "${{ env.REGISTRY_URL }}"/dam-api:latest
          && docker buildx build . --file ./dockerfile/Dockerfile-front --tag "${{ env.REGISTRY_URL }}"/dam-front:latest

      - name: Run Unit Tests
        run: docker run -d -e ENV=TEST --name=dam-api "${{ env.REGISTRY_URL }}"/dam-api:latest
              && docker exec dam-api bash -c 'python -m pytest'

      - name: Login to Registry
        run: echo "${{ env.TOKEN }}" | docker login "${{ env.REGISTRY_URL }}" -u "${{ env.REGISTRY_USER }}" --password-stdin

      - name: Push to Registry
        run: docker push "${{ env.REGISTRY_URL }}"/dam-front:latest
          && docker push "${{ env.REGISTRY_URL }}"/dam-api:latest
