name: CI

# TO UPDATE
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-test-push:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.PROD_REGISTRY_TOKEN || secrets.PREPROD_REGISTRY_TOKEN }}
      REGISTRY_URL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_REGISTRY_URL || secrets.PREPROD_REGISTRY_URL }}
      REGISTRY_USER: ${{ github.ref == 'refs/heads/main' && secrets.PROD_REGISTRY_USER || secrets.PREPROD_REGISTRY_USER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker images
        run: docker buildx build . --file ./dockerfile/Dockerfile-api --tag dam-api:latest
          && docker buildx build . --file ./dockerfile/Dockerfile-front --tag dam-front:latest

      - name: Unit Tests
        run: docker run -d -e ENV=TEST --name=dam-api dam-api:latest
              && docker exec dam-api bash -c 'python -m pytest'

      - name: Login to Registry
        run: echo "${{ env.TOKEN }}" | docker login "${{ env.REGISTRY_URL }}" -u "${{ env.REGISTRY_USER }}" --password-stdin

      - name: Push to Registry
        run: echo 'Todo Push To Registry'