name: CI

# TO UPDATE
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Build docker images 
        run: docker build . --file ./dockerfile/Dockerfile-api --tag dam-api:$(date +%s)
          && docker build . --file ./dockerfile/Dockerfile-front --tag dam-front:$(date +%s)
